title: "Prateek Rajput"
description: "Senior Data Engineer & Backend Engineering Leader"
url: "https://prateek-rajput.com"
baseurl: ""

author:
  name: "Prateek Rajput"
  email: "prateek.rajput3@gmail.com"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - jekyll.log
  - dev-server.sh
  - .jekyll.pid
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - vendor
  - .DS_Store
  - "*.log"
