title: "Prateek Rajput"
description: "Senior Data Engineer & Backend Engineering Leader"
url: "https://prateek-217.github.io"
baseurl: ""

author:
  name: "Prateek Rajput"
  email: "prateek.rajput3@gmail.com"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
